### ISSUE TITLE
call report.php via cron job

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3305]
Hello,

I would like to use a cron job to create a report for one day as a csv file every 5 minutes in the mrbs folder in order to be able to process this file further.

I know the help for the report.php, but unfortunately I always get an error.

Does someone maybe have a correct call to be able to call the report.php via the cron job.

Many Thanks

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2620](https://sourceforge.net/p/mrbs/support-requests/2620)

**Comment by Lithimlin** [comment]
> Here's an example
> 
> ```
> /usr/local/bin/php /home/mrbs/report.php output=1 from_date=2019-01-01 to_date=2020-01-01 sumby=c > summary.csv
> ```
> 
> What are you using? And what's the error you are getting?
> 
> Original comment by: campbell-m

I've tried running this on my MRBS server but I get a fatal error:

```
$ php report.php phase=2 from_date=2024-03-18 to_date=2024-03-24 output=0 output_format=2 sortby=r sumby=d datatable=1 match_confirmed=2

Notice: The config variable $override_locale should now be in BCP 47 format. Please change 'en_DE.utf8' to 'en-DE'. in /var/www/mrbs-code-1.11.4/web/language.inc on line 70

Notice: Server failed to set locale to ["en-DE.UTF-8","en_DE.UTF-8"] for language tag 'en-DE'. in /var/www/mrbs-code-1.11.4/web/language.inc on line 174
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 41<br>
</b>
ini_set(): Session ini settings cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 42<br>
</b>
ini_set(): Session ini settings cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 43<br>
</b>
ini_set(): Session ini settings cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 50<br>
</b>
ini_set(): Session ini settings cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 53<br>
</b>
session_name(): Session name cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 54<br>
</b>
session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 70<br>
</b>
session_set_save_handler(): Session save handler cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 72<br>
</b>
session_start(): Session cannot be started after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 89<br>
</b>
session_set_save_handler(): Session save handler cannot be changed after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 91<br>
</b>
session_start(): Session cannot be started after headers have already been sent<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b>Uncaught exception &#039;Exception&#039; in /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php at line 93<br>
</b>
MRBS: could not start sessions<br>
#0 /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/Session.php(23): MRBS\Session\Session-&gt;init(2592000)<br>
#1 /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/SessionWithLogin.php(31): MRBS\Session\Session-&gt;__construct()<br>
#2 /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/SessionPhp.php(19): MRBS\Session\SessionWithLogin-&gt;__construct()<br>
#3 /var/www/mrbs-code-1.11.4/web/lib/MRBS/Session/SessionFactory.php(14): MRBS\Session\SessionPhp-&gt;__construct()<br>
#4 /var/www/mrbs-code-1.11.4/web/mrbs_auth.inc(33): MRBS\Session\SessionFactory::create(&#039;php&#039;)<br>
#5 /var/www/mrbs-code-1.11.4/web/init.inc(40): MRBS\session()<br>
#6 /var/www/mrbs-code-1.11.4/web/defaultincludes.inc(34): require_once(&#039;/var/www/mrbs-c...&#039;)<br>
#7 /var/www/mrbs-code-1.11.4/web/report.php(18): require(&#039;/var/www/mrbs-c...&#039;)<br>
#8 {main}<br>
<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/functions.inc at line 839<br>
</b>
Cannot modify header information - headers already sent by (output started at /var/www/mrbs-code-1.11.4/web/language.inc:70)<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/functions.inc at line 826<br>
</b>
Cannot modify header information - headers already sent by (output started at /var/www/mrbs-code-1.11.4/web/language.inc:70)<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<b><br>
E_WARNING in /var/www/mrbs-code-1.11.4/web/functions.inc at line 827<br>
</b>
Cannot modify header information - headers already sent by (output started at /var/www/mrbs-code-1.11.4/web/language.inc:70)<br>
MRBS GET: Array<br>
(<br>
)<br>
MRBS POST: Array<br>
(<br>
)<br>
<br>
<!DOCTYPE html>
<!--[if lte IE 9]>
<html lang="en" class="unsupported_browser">
<![endif]-->
<!--[if (!IE)|(gt IE 9)]><!-->
<html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow, noarchive">
<title>Booking System</title>
<link rel="stylesheet" type="text/css" href="jquery/ui/css/jquery-ui.structure.min.css?v=1695570158">
<link rel="stylesheet" type="text/css" href="jquery/ui/css/cupertino/jquery-ui.theme.min.css?v=1695570158">
<link rel="stylesheet" type="text/css" href="jquery/datatables/datatables.min.css?v=1695570158">
<link rel="stylesheet" type="text/css" href="js/flatpickr/css/flatpickr.min.css?v=1695570158">
<link rel="stylesheet" type="text/css" href="jquery/select2/dist/css/select2.min.css?v=1695570158">
<link rel="stylesheet" type="text/css" href="css/mrbs.css.php?v=1695570158">
<link rel="stylesheet" type="text/css" href="css/mrbs-print.css.php?v=1695570158" media="print">
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="css/mrbs-ie.css?v=1695570158">
<![endif]-->
</head>
<body class="">
<div class="unsupported_message">
<header class="banner simple">
<div class="company">
<span>mrbs</span><a href="index.php">Booking System</a>
</div>
</header>
<div class="contents">
<p>Unfortunately your browser isn't supported by MRBS.  You will need to upgrade to a more recent version, or else use another browser.</p>
</div>
</div>
<header class="banner simple">
<div class="company">
<span>mrbs</span><a href="index.php">Booking System</a>
</div>
</header>
<div class="contents">
<p>
Whoops! Unfortunately MRBS has encountered a fatal error.  Please consult your system administrator.</p>
</div>
</body>
</html>
```
Is calling the report.php script directly even supposed to work?

**Comment by campbell-m** [comment]
Yes, it is supposed to work, but you have got two errors you need to fix:

1.  Change the setting for `$override_locale` in your config file from 'en_DE.utf8' to 'en-DE'.
2.  But I don't think you mean 'en-DE', which is why the server could not set that locale.  Do you mean 'de-DE'?

**Comment by Lithimlin** [comment]
Thanks for the quick reply.
I managed to find the correct config file and fix the locale.

However, now I'm getting the login page as HTML back. Do I need to log in after all? If so, I might have misunderstood the conversation above.

**Comment by campbell-m** [comment]
Have you set `$allow_cli = true;` in your config file?

**Comment by Lithimlin** [comment]
Now I have, I missed that flag. It's working now.

One more question though that came up while fixing the locale:
Is there a way to get the language to English but use ISO8601 for the date format?
I managed to make it work with the `$datetime_formats` overrides for everything but input fields.

Cheers

**Comment by campbell-m** [comment]
Which input fields?  Can you give an example?
