### ISSUE TITLE
Installation problem MRBS

### ISSUE THREAD

**Issue by bahijamahfoud** [meeting-room-booking-system/mrbs-code#3642]
when I launch the MRBs page I GET AN ERROR / Oops! MRBS encountered a fatal error. Please consult your system administrator.
and the following errors: 

~~~text
Notice: Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/html/language.inc on line 174

E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 41
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, ini_set(): Headers already sent. You cannot change the session module's ini settings at this time, /var/www/html/lib/MRBS/Session/Session.php, 41, array)
#3 ini_set(session.use_only_cookies, 1) called at [/var/www/html/lib/MRBS/Session/Session.php:41]
#4 MRBS\Session\Session->init(2592000) called at [/var/www/html/lib/MRBS/Session/Session.php:23]
#5 MRBS\Session\Session->__construct() called at [/var/www/html/lib/MRBS/Session/SessionWithLogin.php:31]
#6 MRBS\Session\SessionWithLogin->__construct() called at [/var/www/html/lib/MRBS/Session/SessionPhp.php:19]
#7 MRBS\Session\SessionPhp->__construct() called at [/var/www/html/lib/MRBS/Session/SessionFactory.php:14]
#8 MRBS\Session\SessionFactory::create(php) called at [/var/www/html/mrbs_auth.inc:33]
#9 MRBS\session() called at [/var/www/html/init.inc:40]
#10 require_once(/var/www/html/init.inc) called at [/var/www/html/defaultincludes.inc:34]
#11 require(/var/www/html/defaultincludes.inc) called at [/var/www/html/search.php:11]

E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 42
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, ini_set(): Headers already sent. You cannot change the session module's ini settings at this time, /var/www/html/lib/MRBS/Session/Session.php, 42, array)
#3 ini_set(session.use_strict_mode, 1) called at [/var/www/html/lib/MRBS/Session/Session.php:42]
#4 MRBS\Session\Session->init(2592000) called at [/var/www/html/lib/MRBS/Session/Session.php:23]
#5 MRBS\Session\Session->__construct() called at [/var/www/html/lib/MRBS/Session/SessionWithLogin.php:31]
#6 MRBS\Session\SessionWithLogin->__construct() called at [/var/www/html/lib/MRBS/Session/SessionPhp.php:19]
#7 MRBS\Session\SessionPhp->__construct() called at [/var/www/html/lib/MRBS/Session/SessionFactory.php:14]
#8 MRBS\Session\SessionFactory::create(php) called at [/var/www/html/mrbs_auth.inc:33]
#9 MRBS\session() called at [/var/www/html/init.inc:40]
#10 require_once(/var/www/html/init.inc) called at [/var/www/html/defaultincludes.inc:34]
#11 require(/var/www/html/defaultincludes.inc) called at [/var/www/html/search.php:11]

E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 43
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, ini_set(): Headers already sent. You cannot change the session module's ini settings at this time, /var/www/html/lib/MRBS/Session/Session.php, 43, array)
#3 ini_set(session.use_trans_sid, 0) called at [/var/www/html/lib/MRBS/Session/Session.php:43]
#4 MRBS\Session\Session->init(2592000) called at [/var/www/html/lib/MRBS/Session/Session.php:23]
#5 MRBS\Session\Session->__construct() called at [/var/www/html/lib/MRBS/Session/SessionWithLogin.php:31]
#6 MRBS\Session\SessionWithLogin->__construct() called at [/var/www/html/lib/MRBS/Session/SessionPhp.php:19]
#7 MRBS\Session\SessionPhp->__construct() called at [/var/www/html/lib/MRBS/Session/SessionFactory.php:14]
#8 MRBS\Session\SessionFactory::create(php) called at [/var/www/html/mrbs_auth.inc:33]
#9 MRBS\session() called at [/var/www/html/init.inc:40]
#10 require_once(/var/www/html/init.inc) called at [/var/www/html/defaultincludes.inc:34]
#11 require(/var/www/html/defaultincludes.inc) called at [/var/www/html/search.php:11]

E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 50
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, ini_set(): Headers already sent. You cannot change the session module's ini settings at this time, /var/www/html/lib/MRBS/Session/Session.php, 50, array)
#3 ini_set(session.gc_maxlifetime, 2592000) called at [/var/www/html/lib/MRBS/Session/Session.php:50]
#4 MRBS\Session\Session->init(2592000) called at [/var/www/html/lib/MRBS/Session/Session.php:23]
#5 MRBS\Session\Session->__construct() called at [/var/www/html/lib/MRBS/Session/SessionWithLogin.php:31]
#6 MRBS\Session\SessionWithLogin->__construct() called at [/var/www/html/lib/MRBS/Session/SessionPhp.php:19]
#7 MRBS\Session\SessionPhp->__construct() called at [/var/www/html/lib/MRBS/Session/SessionFactory.php:14]
#8 MRBS\Session\SessionFactory::create(php) called at [/var/www/html/mrbs_auth.inc:33]
#9 MRBS\session() called at [/var/www/html/init.inc:40]
#10 require_once(/var/www/html/init.inc) called at [/var/www/html/defaultincludes.inc:34]
#11 require(/var/www/html/defaultincludes.inc) called at [/var/www/html/search.php:11]

E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 53
session_name(): Cannot change session name when headers already sent
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, session_name(): Cannot change session name when headers already sent, /var/www/html/lib/MRBS/Session/Session.php, 53, array)
#3 session_name(MRBS_SESSID) called at [/var/www/html/lib/MRBS/Session/Session.php:53]
#4 MRBS\Session\Session->init(2592000) called at [/var/www/html/lib/MRBS/Session/Session.php:23]
#5 MRBS\Session\Session->__construct() called at [/var/www/html/lib/MRBS/Session/SessionWithLogin.php:31]
#6 MRBS\Session\SessionWithLogin->__construct() called at [/var/www/html/lib/MRBS/Session/SessionPhp.php:19]
#7 MRBS\Session\SessionPhp->__construct() called at [/var/www/html/lib/MRBS/Session/SessionFactory.php:14]
#8 MRBS\Session\SessionFactory::create(php) called at [/var/www/html/mrbs_auth.inc:33]
#9 MRBS\session() called at [/var/www/html/init.inc:40]
#10 require_once(/var/www/html/init.inc) called at [/var/www/html/defaultincludes.inc:34]
#11 require(/var/www/html/defaultincludes.inc) called at [/var/www/html/search.php:11]

E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 54
session_set_cookie_params(): Cannot change session cookie parameters when headers already sent
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, session_set_cookie_params(): Cannot change session cookie parameters when headers already sent, /var/www/html/lib/MRBS/Session/Session.php, 54, array)
#3 session_set_cookie_params(2592000, /) called at [/var/www/html/lib/MRBS/Session/Session.php:54]
#4 MRBS\Session\Session->init(2592000) called at [/var/www/html/lib/MRBS/Session/Session.php:23]
#5 MRBS\Session\Session->__construct() called at [/var/www/html/lib/MRBS/Session/SessionWithLogin.php:31]
#6 MRBS\Session\SessionWithLogin->__construct() called at [/var/www/html/lib/MRBS/Session/SessionPhp.php:19]
#7 MRBS\Session\SessionPhp->__construct() called at [/var/www/html/lib/MRBS/Session/SessionFactory.php:14]
#8 MRBS\Session\SessionFactory::create(php) called at [/var/www/html/mrbs_auth.inc:33]
#9 MRBS\session() called at [/var/www/html/init.inc:40]
#10 require_once(/var/www/html/init.inc) called at [/var/www/html/defaultincludes.inc:34]
#11 require(/var/www/html/defaultincludes.inc) called at [/var/www/html/search.php:11]
Uncaught exception 'MRBS\Exception' in /var/www/html/lib/MRBS/DBFactory.php at line 39
Undefined class constant 'PDO::MYSQL_ATTR_FOUND_ROWS'
#0 /var/www/html/dbsys.inc(63): MRBS\DBFactory::create('mysql', 'db', 'mrbs', 'mrbs', 'mrbs', false, NULL, Array)
#1 /var/www/html/dbsys.inc(74): MRBS\db()
#2 /var/www/html/lib/MRBS/Session/Session.php(56): MRBS\db_schema_version()
#3 /var/www/html/lib/MRBS/Session/Session.php(23): MRBS\Session\Session->init(2592000)
#4 /var/www/html/lib/MRBS/Session/SessionWithLogin.php(31): MRBS\Session\Session->__construct()
#5 /var/www/html/lib/MRBS/Session/SessionPhp.php(19): MRBS\Session\SessionWithLogin->__construct()
#6 /var/www/html/lib/MRBS/Session/SessionFactory.php(14): MRBS\Session\SessionPhp->__construct()
#7 /var/www/html/mrbs_auth.inc(33): MRBS\Session\SessionFactory::create('php')
#8 /var/www/html/init.inc(40): MRBS\session()
#9 /var/www/html/defaultincludes.inc(34): require_once('/var/www/html/i...')
#10 /var/www/html/search.php(11): require('/var/www/html/d...')
#11 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:262]
#2 MRBS\output_exception_error(object) called at [/var/www/html/functions_error.inc:270]
#3 MRBS\exception_handler(object)

E_WARNING in /var/www/html/functions.inc at line 839
Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174)
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174), /var/www/html/functions.inc, 839, array)
#3 header(Content-Type: text/html; charset=utf-8) called at [/var/www/html/functions.inc:839]
#4 MRBS\http_headers(array) called at [/var/www/html/Themes/default/header.inc:625]
#5 MRBS\print_theme_header(NULL, true, false) called at [/var/www/html/functions.inc:882]
#6 MRBS\print_header(NULL, true) called at [/var/www/html/functions.inc:851]
#7 MRBS\print_simple_header() called at [/var/www/html/functions_error.inc:295]
#8 MRBS\fatal_error(Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator.) called at [/var/www/html/functions_error.inc:285]
#9 MRBS\exception_handler(object)

E_WARNING in /var/www/html/functions.inc at line 826
Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174)
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174), /var/www/html/functions.inc, 826, array)
#3 header(Pragma: no-cache) called at [/var/www/html/functions.inc:826]
#4 MRBS\expires_header(0) called at [/var/www/html/functions.inc:842]
#5 MRBS\http_headers(array) called at [/var/www/html/Themes/default/header.inc:625]
#6 MRBS\print_theme_header(NULL, true, false) called at [/var/www/html/functions.inc:882]
#7 MRBS\print_header(NULL, true) called at [/var/www/html/functions.inc:851]
#8 MRBS\print_simple_header() called at [/var/www/html/functions_error.inc:295]
#9 MRBS\fatal_error(Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator.) called at [/var/www/html/functions_error.inc:285]
#10 MRBS\exception_handler(object)

E_WARNING in /var/www/html/functions.inc at line 827
Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174)
MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [/var/www/html/functions_error.inc:219]
#1 MRBS\output_error() called at [/var/www/html/functions_error.inc:249]
#2 MRBS\error_handler(2, Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174), /var/www/html/functions.inc, 827, array)
#3 header(Expires: Mon, 26 Jul 1997 05:00:00 GMT) called at [/var/www/html/functions.inc:827]
#4 MRBS\expires_header(0) called at [/var/www/html/functions.inc:842]
#5 MRBS\http_headers(array) called at [/var/www/html/Themes/default/header.inc:625]
#6 MRBS\print_theme_header(NULL, true, false) called at [/var/www/html/functions.inc:882]
#7 MRBS\print_header(NULL, true) called at [/var/www/html/functions.inc:851]
#8 MRBS\print_simple_header() called at [/var/www/html/functions_error.inc:295]
#9 MRBS\fatal_error(Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator.) called at [/var/www/html/functions_error.inc:285]
#10 MRBS\exception_handler(object)
~~~

**Comment by campbell-m** [comment]
There are two problems:

1. The 'en' locale is not available on your server.  Either install it or else set `$override_locale` to a locale that is available.
2. It looks like the PDO MySQL driver is not enabled on your server.

**Comment by campbell-m** [comment]
Have you fixed the locale problem?  What errors are you getting now?

**Comment by bahijamahfoud** [comment]
I still have all these mistakes  :/

Notice: Server failed to set locale to ["fr-FR.UTF-8","fr_FR.UTF-8"] for language tag 'fr-FR'. in /var/www/html/language.inc on line 174

E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 41
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 42
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 43
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 50
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 53
session_name(): Cannot change session name when headers already sent
MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/lib/MRBS/Session/Session.php at line 54
session_set_cookie_params(): Cannot change session cookie parameters when headers already sent
MRBS GET: Array
(
)
MRBS POST: Array
(
)

Uncaught exception 'MRBS\Exception' in /var/www/html/lib/MRBS/DBFactory.php at line 39
Undefined class constant 'PDO::MYSQL_ATTR_FOUND_ROWS'
#0 /var/www/html/dbsys.inc(63): MRBS\DBFactory::create('mysql', 'db', 'mrbs', 'mrbs', 'mrbs', false, NULL, Array)
#1 /var/www/html/dbsys.inc(74): MRBS\db()
#2 /var/www/html/lib/MRBS/Session/Session.php(56): MRBS\db_schema_version()
#3 /var/www/html/lib/MRBS/Session/Session.php(23): MRBS\Session\Session->init(2592000)
#4 /var/www/html/lib/MRBS/Session/SessionWithLogin.php(31): MRBS\Session\Session->__construct()
#5 /var/www/html/lib/MRBS/Session/SessionPhp.php(19): MRBS\Session\SessionWithLogin->__construct()
#6 /var/www/html/lib/MRBS/Session/SessionFactory.php(14): MRBS\Session\SessionPhp->__construct()
#7 /var/www/html/mrbs_auth.inc(33): MRBS\Session\SessionFactory::create('php')
#8 /var/www/html/init.inc(40): MRBS\session()
#9 /var/www/html/defaultincludes.inc(34): require_once('/var/www/html/i...')
#10 /var/www/html/index.php(8): require('/var/www/html/d...')
#11 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/functions.inc at line 839
Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174)
MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/functions.inc at line 826
Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174)
MRBS GET: Array
(
)
MRBS POST: Array
(
)


E_WARNING in /var/www/html/functions.inc at line 827
Cannot modify header information - headers already sent by (output started at /var/www/html/language.inc:174)
MRBS GET: Array
(
)
MRBS POST: Array

**Comment by campbell-m** [comment]
What have you changed?

It looks like you haven't got the fr-FR locale installed on your server.  Run `locale -a` from the command line to find out what locales are installed.

**Comment by bahijamahfoud** [comment]
after executing the command local  -a I got these locals for france: 
francais
fr_BE
fr_BE@euro
fr_BE.iso88591
fr_BE.iso885915@euro
fr_BE.utf8
fr_CA
fr_CA.iso88591
fr_CA.utf8
fr_CH
fr_CH.iso88591
fr_CH.utf8
french
fr_FR
fr_FR@euro
fr_FR.iso88591
fr_FR.iso885915@euro
fr_FR.utf8
fr_LU
fr_LU@euro
fr_LU.iso88591
fr_LU.iso885915@euro
fr_LU.utf8

**Comment by bahijamahfoud** [comment]
I added this command : $override_locale = 'fr-FR';   in my file config.inc.php

**Comment by campbell-m** [comment]
What operating system and version is your server running?

**Comment by bahijamahfoud** [comment]
CentOS Linux release 7.9.2009

**Comment by bahijamahfoud** [comment]
CentOS Linux release 7.9.2009

**Comment by campbell-m** [comment]
Can you run the attached test program on your server please and post the output here?  You will need to unzip the file first.
[test.zip](https://github.com/meeting-room-booking-system/mrbs-code/files/14885561/test.zip)


The output should look something like:

~~~text
PHP: 7.2.34

fr-FR.UTF-8: bool(false)
fr_FR.UTF-8: string(11) "fr_FR.UTF-8"
fr-FR.utf8: bool(false)
fr_FR.utf8: string(10) "fr_FR.utf8"
fr.UTF-8: bool(false)
fr.utf8: bool(false)
~~~

**Comment by bahijamahfoud** [comment]
thank you very much for your help, we solved the problem.

**Comment by campbell-m** [comment]
What was the solution?  (It will help other people with the same problem.)

**Comment by bahijamahfoud** [comment]
we work more with the files of the application, but rather with a docker image.

**Comment by bahijamahfoud** [comment]
in fact we haven’t found a solution for the problem, but we have changed, we are now working with a docker image.

**Comment by campbell-m** [comment]
OK.  It would still be helpful for me if you could run the test program if you get a chance.

**Comment by Martin1088** [comment]
Hi
I got into the same issue.

Server failed to set locale to ["en.UTF-8", "en-GB.UTF-8", "en_GB.UTF-8"] for language tag 'en'. in /var/www/html/language.ing on line 176
I just ran the docker compose
I will try the solutions

**Comment by campbell-m** [comment]
> Hi
> I got into the same issue.

> Server failed to set locale to ["en.UTF-8", "en-GB.UTF-8", "en_GB.UTF-8"] for language tag 'en'. in /var/www/html/language.ing on line 176
> I just ran the docker compose
> I will try the solutions

See also Issue #3639
