### ISSUE TITLE
Issues with SMTP

### ISSUE THREAD

**Issue by sjzbim** [meeting-room-booking-system/mrbs-code#3796]
Dear developer, I tried to use SMTP email reminder, but I still got errors after multiple attempts over the past week. I hope you can give me some help. Thank you very much.
Here's my config

![image](https://github.com/user-attachments/assets/60303b25-a275-4ca7-b9a9-50daa9e01182)

When I try to reserve a meeting room, fill in the form and save, an error occurs, showing the following. I cannot find the Log file.

~~~text
Uncaught exception 'TypeError' in /var/www/html/lib/MRBS/Intl/IntlDateFormatter.php at line 251
Argument 3 passed to MRBS\Intl\IntlDateFormatter::doStrftimePlus() must be of the type string or null, bool given, called in /var/www/html/lib/MRBS/Intl/IntlDateFormatter.php on line 226
#0 /var/www/html/lib/MRBS/Intl/IntlDateFormatter.php(226): MRBS\Intl\IntlDateFormatter::doStrftimePlus('%A, %B %i, %Y a...', 1735207200, false)
#1 /var/www/html/lib/MRBS/Intl/IntlDateFormatter.php(117): MRBS\Intl\IntlDateFormatter->strftimePlus('%A, %B %i, %Y a...', 1735207200)
#2 /var/www/html/language.inc(846): MRBS\Intl\IntlDateFormatter->format(1735207200)
#3 /var/www/html/functions_mail.inc(123): MRBS\datetime_format(Array, 1735207200, 'en')
#4 /var/www/html/functions_mail.inc(137): MRBS\getMailTimeDateString(1735207200)
#5 /var/www/html/functions_mail.inc(523): MRBS\getMailDateString(1735207200)
#6 /var/www/html/functions_mail.inc(917): MRBS\create_body(Array, Array, false, false, 'book', Array, false, NULL)
#7 /var/www/html/mrbs_sql.inc(2852): MRBS\notifyAdminOnBooking(Array, Array, true, false, Array)
#8 /var/www/html/edit_entry_handler.php(839): MRBS\mrbsMakeBookings(Array, NULL, false, false, NULL, true, false)
#9 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
    [MAX_FILE_SIZE] => 2097152
    [csrf_token] => 7111b2542629f9e801c1a5dce8ebf30adbfccd32e16edec2658923bc1e3618b8
    [returl] => /index.php
    [rep_id] => 0
    [edit_series] => 0
    [create_by] => test1
    [name] => 11
    [description] => 1
    [start_date] => 2024-12-26
    [start_seconds] => 36000
    [end_date] => 2024-12-26
    [end_seconds] => 43200
    [rooms] => Array
        (
            [0] => 1
        )

    [type] => I
    [confirmed] => 1
    [rep_type] => 0
    [rep_day] => Array
        (
            [0] => 4
        )

    [month_type] => 0
    [month_absolute] => 26
    [month_relative_ord] => 4
    [month_relative_day] => TH
    [rep_interval] => 1
    [rep_end_date] => 2024-12-26
)
MRBS SESSION: Array
(
    [last_page] => /edit_entry.php?view=day&year=2024&month=12&day=26&area=1&room=1&hour=10&minute=0
    [this_page] => /edit_entry_handler.php
    [csrf_token] => 7111b2542629f9e801c1a5dce8ebf30adbfccd32e16edec2658923bc1e3618b8
    [user] => MRBS\User Object
        (
            [username] => test1
            [display_name] => test1
            [email] => ***@qq.com
            [level] => 1
            [data:protected] => Array
                (
                    [id] => 2
                    [password_hash] => $2y$10$qyJZ3aUasduE0fKjasdXwFCOLu2Nhasd8x3HasdhHx2xsasd5dY7ioLvs32
                    [timestamp] => 2024-12-26 08:48:16
                    [last_login] => 1735202909
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)


E_WARNING in /var/www/html/functions.inc at line 841
Cannot modify header information - headers already sent by (output started at /var/www/html/functions_error.inc:231)
MRBS GET: Array
(
)
MRBS POST: Array
(
    [MAX_FILE_SIZE] => 2097152
    [csrf_token] => 7111b2542634801c1a5dce8esdrf23bfccd32e16edec2658923bc1e3618b8
    [returl] => /index.php
    [rep_id] => 0
    [edit_series] => 0
    [create_by] => test1
    [name] => 11
    [description] => 1
    [start_date] => 2024-12-26
    [start_seconds] => 36000
    [end_date] => 2024-12-26
    [end_seconds] => 43200
    [rooms] => Array
        (
            [0] => 1
        )

    [type] => I
    [confirmed] => 1
    [rep_type] => 0
    [rep_day] => Array
        (
            [0] => 4
        )

    [month_type] => 0
    [month_absolute] => 26
    [month_relative_ord] => 4
    [month_relative_day] => TH
    [rep_interval] => 1
    [rep_end_date] => 2024-12-26
)
MRBS SESSION: Array
(
    [last_page] => /edit_entry.php?view=day&year=2024&month=12&day=26&area=1&room=1&hour=10&minute=0
    [this_page] => /edit_entry_handler.php
    [csrf_token] => 7111b2542629fsfdf1c1afghh5dce0adbfccd32e1fshdec2658923bc1e3618b8
    [user] => MRBS\User Object
        (
            [username] => test1
            [display_name] => test1
            [email] => ***@qq.com
            [level] => 1
            [data:protected] => Array
                (
                    [id] => 2
                    [password_hash] => $2y$10$qyJHQvYZ3aUuE0fKjXwFCOLu2Nh8x3HmhHx2k2DFjz5dY7ioLvs32
                    [timestamp] => 2024-12-26 08:48:16
                    [last_login] => 1735202909
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)


E_WARNING in /var/www/html/functions.inc at line 828
Cannot modify header information - headers already sent by (output started at /var/www/html/functions_error.inc:231)
MRBS GET: Array
(
)
MRBS POST: Array
(
    [MAX_FILE_SIZE] => 2097152
    [csrf_token] => 7111b2542629f9e801csafdce8ebf30adqewd32eereec265er923bc1e3618b8
    [returl] => /index.php
    [rep_id] => 0
    [edit_series] => 0
    [create_by] => test1
    [name] => 11
    [description] => 1
    [start_date] => 2024-12-26
    [start_seconds] => 36000
    [end_date] => 2024-12-26
    [end_seconds] => 43200
    [rooms] => Array
        (
            [0] => 1
        )

    [type] => I
    [confirmed] => 1
    [rep_type] => 0
    [rep_day] => Array
        (
            [0] => 4
        )

    [month_type] => 0
    [month_absolute] => 26
    [month_relative_ord] => 4
    [month_relative_day] => TH
    [rep_interval] => 1
    [rep_end_date] => 2024-12-26
)
MRBS SESSION: Array
(
    [last_page] => /edit_entry.php?view=day&year=2024&month=12&day=26&area=1&room=1&hour=10&minute=0
    [this_page] => /edit_entry_handler.php
    [csrf_token] => 7111b2542629f9e801c1a5bf30adbfccd32e12658923bc1e3618b8
    [user] => MRBS\User Object
        (
            [username] => test1
            [display_name] => test1
            [email] => ***@qq.com
            [level] => 1
            [data:protected] => Array
                (
                    [id] => 2
                    [password_hash] => $2y$10$qyJUuE0fsdOLu2NhHz5dY7ioLvs32
                    [timestamp] => 2024-12-26 08:48:16
                    [last_login] => 1735202909
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)


E_WARNING in /var/www/html/functions.inc at line 829
Cannot modify header information - headers already sent by (output started at /var/www/html/functions_error.inc:231)
MRBS GET: Array
(
)
MRBS POST: Array
(
    [MAX_FILE_SIZE] => 2097152
    [csrf_token] => 7111b2542c1a5dce8ebf332e16edec223bc1e3618b8
    [returl] => /index.php
    [rep_id] => 0
    [edit_series] => 0
    [create_by] => test1
    [name] => 11
    [description] => 1
    [start_date] => 2024-12-26
    [start_seconds] => 36000
    [end_date] => 2024-12-26
    [end_seconds] => 43200
    [rooms] => Array
        (
            [0] => 1
        )

    [type] => I
    [confirmed] => 1
    [rep_type] => 0
    [rep_day] => Array
        (
            [0] => 4
        )

    [month_type] => 0
    [month_absolute] => 26
    [month_relative_ord] => 4
    [month_relative_day] => TH
    [rep_interval] => 1
    [rep_end_date] => 2024-12-26
)
MRBS SESSION: Array
(
    [last_page] => /edit_entry.php?view=day&year=2024&month=12&day=26&area=1&room=1&hour=10&minute=0
    [this_page] => /edit_entry_handler.php
    [csrf_token] => 7111b2541a5dce8ebf30adbfccc2658923bc1e3618b8
    [user] => MRBS\User Object
        (
            [username] => test1
            [display_name] => test1
            [email] => ***@qq.com
            [level] => 1
            [data:protected] => Array
                (
                    [id] => 2
                    [password_hash] => $2y$10$UuE0fKjXwFCO3HmhHx2k2Y7ioLvs32
                    [timestamp] => 2024-12-26 08:48:16
                    [last_login] => 1735202909
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)
~~~

**Comment by campbell-m** [comment]
Which version of MRBS are you using?  And have you made any changes to it?

**Comment by campbell-m** [comment]
Are you getting any other error messages, eg about locales?

**Comment by sjzbim** [comment]
> Are you getting any other error messages, eg about locales?

If I don't enable smtp, there will be no problem. The time is not right, but it can be configured.

**Comment by campbell-m** [comment]
I think the problem is that your server doesn't have the 'en' locale installed, which is the locale being used for mail messages.  There are three things you could do:

1. Install the 'en' locale on your server; or
2. Enable PHP's 'intl' extension on your server; or
3. Set `$mail_settings['admin_lang']` to a locale that is supported on your server.

In the meantime I have improved the error handling in [2059cc0](https://github.com/meeting-room-booking-system/mrbs-code/commit/2059cc0fe0f871f329c22227c3c72d36f9c6c47f).

**Comment by sjzbim** [comment]
> I think the problem is that your server doesn't have the 'en' locale installed, which is the locale being used for mail messages.  There are three things you could do:
> 
> 
> 
> 1. Install the 'en' locale on your server; or
> 
> 2. Enable PHP's 'intl' extension on your server; or
> 
> 3. Set `$mail_settings['admin_lang']` to a locale that is supported on your server.
> 
> 
> 
> In the meantime I have improved the error handling in [2059cc0](https://github.com/meeting-room-booking-system/mrbs-code/commit/2059cc0fe0f871f329c22227c3c72d36f9c6c47f).

Thank you very much for your help. I will try to modify the configuration later and give you feedback.

**Comment by sjzbim** [comment]
> 1. 你的服务器上安装“en”语言环境

I have updated "IntlDateFormatter.php" according to [2059cc0](https://github.com/meeting-room-booking-system/mrbs-code/commit/2059cc0fe0f871f329c22227c3c72d36f9c6c47f). After several attempts, finally, I set $mail_settings['admin_lang'] to 'zh-cn' , now the smtp service is normal. Thank you very much.
